// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDzxWrf2VjMyUAM2zlHKC5VpNEDyrLpZQ',
    appId: '1:171901351805:web:952384dfd8c9b122b87e14',
    messagingSenderId: '171901351805',
    projectId: 'mochat-7a122',
    authDomain: 'mochat-7a122.firebaseapp.com',
    storageBucket: 'mochat-7a122.firebasestorage.app',
    measurementId: 'G-NZ042SW4L5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7EUcnNLXYiVSR70ITT2zm83xp5SnNe1M',
    appId: '1:171901351805:ios:b433899403eb6a05b87e14',
    messagingSenderId: '171901351805',
    projectId: 'mochat-7a122',
    storageBucket: 'mochat-7a122.firebasestorage.app',
    iosBundleId: 'com.example.moChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDzxWrf2VjMyUAM2zlHKC5VpNEDyrLpZQ',
    appId: '1:171901351805:web:5bf24362962d9e7fb87e14',
    messagingSenderId: '171901351805',
    projectId: 'mochat-7a122',
    authDomain: 'mochat-7a122.firebaseapp.com',
    storageBucket: 'mochat-7a122.firebasestorage.app',
    measurementId: 'G-NGJJHKLB1C',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7EUcnNLXYiVSR70ITT2zm83xp5SnNe1M',
    appId: '1:171901351805:ios:b433899403eb6a05b87e14',
    messagingSenderId: '171901351805',
    projectId: 'mochat-7a122',
    storageBucket: 'mochat-7a122.firebasestorage.app',
    iosBundleId: 'com.example.moChat',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXEaJMPkuWrredhgF3RJVsE--r8CLWtSQ',
    appId: '1:171901351805:android:bf9b1c01e829c67fb87e14',
    messagingSenderId: '171901351805',
    projectId: 'mochat-7a122',
    storageBucket: 'mochat-7a122.firebasestorage.app',
  );
}
